backend:
  name: github
  repo: junokira/kk  # ← 🔁 change this to your actual repo
  branch: main                         # or 'master', depending on your default branch

media_folder: "static/uploads"         # where uploaded images are stored (inside the repo)
public_folder: "/static/uploads"       # how they're referenced in HTML

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Excerpt", name: "excerpt", widget: "text", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
